name: 'Save bundle report'

on:
  pull_request:
    branches:
      - 'master'

jobs:
  composite:
    name: 'composite'
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS v18.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.12.0'

      - name: Checkout develop
        uses: actions/checkout@v3

      - name: Get branch name
        id: getBranch
        run: echo "result=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Show pull request id
        run: echo ${{ github.event.pull_request.number }}

      - name: Save report
        if: ${{ github.event.pull_request.merged }}
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch origin ${{ steps.getBranch.outputs.result }}:${{ steps.getBranch.outputs.result }}
          git pull origin ${{ steps.getBranch.outputs.result }} --rebase
          git checkout ${{ steps.getBranch.outputs.result }}

          echo { "fileName": "125" } > bundle-report.json

          git add bundle-report.json
          git commit -m "test: [autocommit] Save bundle report to ./bundle-report.json"
          git push origin HEAD:${{ steps.getBranch.outputs.result }}
