name: 'Save bundle report'

on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - '*'

jobs:
  main:
    name: 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS v18.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.12.0'

      - name: Checkout develop
        uses: actions/checkout@v3

      - name: Get branch name
        id: getBranch
        run: echo "result=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - run: echo 'Hello!'

      - name: Save report
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

          echo { "fileName": "235" } > bundle-report.json

          git add bundle-report.json
          git commit -m "test: [autocommit] Save bundle report to ./bundle-report.json"
          git push
